clone:
  git:
    image: plugins/git
    depth: 1
pipeline:
  build_step:
    image: plugins/docker
    username: ijiankang@ihealthlabs.com.cn
    password: iHealthStrategy2018
    registry: registry.cn-beijing.aliyuncs.com
    repo: registry.cn-beijing.aliyuncs.com/ihealthlabs/pigeon
    mirror: 'https://t8ngg3ge.mirror.aliyuncs.com'
    tag:
      - '${DRONE_BUILD_NUMBER}'
      - latest
    dockerfile: Dockerfile
    when:
      branch: develop
      event: push
  build_step:
    image: plugins/docker
    username: ijiankang@ihealthlabs.com.cn
    password: iHealthStrategy2018
    registry: registry.cn-beijing.aliyuncs.com
    repo: registry.cn-beijing.aliyuncs.com/ihealthlabs/pigeon
    mirror: 'https://t8ngg3ge.mirror.aliyuncs.com'
    tag:
      - '${DRONE_BUILD_NUMBER}-master'
      - master
    dockerfile: Dockerfile
    when:
      branch: master
      event: push
  report-build:
    image: clem109/drone-wechat
    secrets:
      - plugin_corp_secret
      - plugin_corpid
      - plugin_agent_id
    title: '${DRONE_REPO_NAME}'
    description: |
      构建序列: ${DRONE_BUILD_NUMBER}失败。鸽子已坠毁，点击卡片查询详细信息。
    msg_url: '${DRONE_BUILD_LINK}'
    btn_txt: 查看详情
    when:
      status:
        - failure
  rancher:
    image: peloton/drone-rancher
    url: 'http://rancher.ihealthcn.com/v2-beta/projects/1a46'
    access_key: FC6450BBAC9464CD0069
    secret_key: 2mbbTGC2rHFV4kghdYfZwDfjmbsR94KwKDhcaWZ5
    service: gtzh-stg/pigeon
    docker_image: 'registry.cn-beijing.aliyuncs.com/ihealthlabs/pigeon:latest'
    batch_size: 1
    timeout: 600
    confirm: true
    when:
      branch: develop
      event: push
  report-deploy:
    image: clem109/drone-wechat
    secrets:
      - plugin_corp_secret
      - plugin_corpid
      - plugin_agent_id
    title: '${DRONE_REPO_NAME}'
    description: |
      构建序列: ${DRONE_BUILD_NUMBER} 部署成功！ 🕊🕊🕊🕊🕊🕊🕊🕊🕊🕊！
      更新内容: ${DRONE_COMMIT_MESSAGE}
    msg_url: 'http://120.92.88.112:7001/'
    btn_txt: 查看运行状况
    when:
      branch: develop
      status:
        - success
