# This should bring up a stateless docker container ready for deployment
version: '3'
services:
  api:
    build: .
    working_dir: /usr/src/app
    ports:
      - "3080:3080"
    restart: always
    environment:
      - MONGO_URL=mongodb://paperKingByiHealth:djsdF3fQa@120.131.8.26:27017,120.131.8.27:27017,120.131.8.46:27017,mongoprod1.ihealthcn.com:27017,mongoprod2.ihealthcn.com:27017,mongoprod3.ihealthcn.com:27017/paper-king?replicaSet=iHealthMongo
      - SECRET=8B8kMWAunyMhxM9q9OhMVCJiXpxBIqpo
      - JWT_SECRET=tctocFi4FLDZtLcbwmxgRJmUj3RHCWwK
      - AUTH=TRUE
      - PORT=3080
      - NODE_ENV=production
      - RIGHTEOUS_RAVEN_URL=https://raven.ihealthlabs.com.cn
      - RIGHTEOUS_RAVEN_ID=hwX6aOr1
      - RIGHTEOUS_RAVEN_KEY=af3da1c0-5cd9-11e7-8401-fb7c0283f83d
      - APP_ID=wx915efa8b538a4df4
      - APP_SECRET=d7be675b1fa83094a446087a90cf4f76