# This should bring up a docker container with a volume mapped to dist folder
# then the command should ensure the dist folder is kept up to date on changes maybe nodemon
version: '3'
services:
  api:
    image: node:7.7.2-alpine
    volumes:
      - yarn:/root/.cache/yarn
      - ./:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "5000:3080"
    command: yarn build && yarn watch

volumes:
  yarn: