# This should bring up a stateless docker container ready for deployment
version: '3'
services:
  api:
    build: .
    working_dir: /usr/src/app
    ports:
      - "3080:3080"
    restart: always
    environment:
      - MONGODB_URL=mongodb://paperKingByiHealth:djsdF3fQa@120.131.8.26:27017,120.131.8.27:27017,120.131.8.46:27017/paper-king?replicaSet=iHealthMongo
      - SECRET=8B8kMWAunyMhxM9q9OhMVCJiXpxBIqpo