# This should bring up a docker container with a volume mapped to dist folder
# then the command should ensure the dist folder is kept up to date on changes maybe nodemon
version: '3'
services:
  api:
    image: node:8.0.0-alpine
    volumes:
      - yarn:/root/.cache/yarn
      - ./:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "3080:3080"
    command: yarn build && yarn watch
    environment:
      - MONGO_URL=mongodb://paperKingDevelopingByiHealth:d3Wrg40dE@120.131.8.26:27017/paper-king-developing
      - SECRET=8B8kMWAunyMhxM9q9OhMVCJiXpxBIqpo
      - PORT=3080
      - NODE_ENV=development

volumes:
  yarn: