type IntelligentQA {
  matched: Boolean
  message: String
  qa: [QA]
}

type QA {
  id: ID!
  esorce: String
  q: String
  a: String
}

# 新增QA类型
type QAAddition {
  _id: ID!
  q: String!
  a: String!
  patientId: ID!
  questioner: String!
  hospital: String!
  msgId: ID!
  cdeId: ID!
  cdeName: String!
  approved: Int!
  approvedUser: String
  createdAt: Date!
  approvedAt: Date
}

type QAListReponse {
  recordsCount: Int!
  totalPage: Int!
  pageIndex: Int!
  pageSize: Int!
  records: [QAAddition]!
}
