input AppointmentInput {
  _id: ID!
  patientId: ID!
  source: String
  appointmentTime: Date
  type: String
  nickname: String
  hisNumber: String
  mobile: String
  confirmStatus: String
  note: String
  blood: Boolean
  footAt: Boolean
  eyeGroundAt: Boolean
  insulinAt: Boolean
  nutritionAt: Boolean
  healthTech: Boolean
  quantizationAt: Boolean
}

type Appointment {
  _id: ID
  source: String
  appointmentTime: Date
  isTelephoneFollowUp: Boolean
  isOutPatient: Boolean
  status: Int
  type: String
  nickname: String
  hisNumber: String
  mobile: String
  createdAt: Date
  expectedTime: Date
  patientId: ID!
  updatedAt: Date
  confirmStatus: String
  institutionId: ID
  healthCareTeamId: ID
  note: String
  blood: Boolean
  footAt: Boolean
  eyeGroundAt: Boolean
  insulinAt: Boolean
  nutritionAt: Boolean
  healthTech: Boolean
  quantizationAt: Boolean
  inValueRange: [Date]
  patientUserInfoCompleted: Boolean
  treatmentStateId: ID
}

type DailyAppointment {
  date: String! # YYYY-MM-DD
  count: Int!
  details: [TeamAppointments!]
}

type TeamAppointments {
  healthCareTeam: HealthCareTeam
  count: Int!
}

type AdditionInfo {
  flag: String
  outpatientId: String
  additions: [Appointment]
  nextAppointment: Appointment
  mgtOutpatientId: ID
  mgtAppointmentTime: Date
}

type AppointmentResult {
  patientId: ID
  treatmentStateId: ID
}

extend type Query {
  getAdditionInfo(patientId: ID!, appointmentTime: Date): AdditionInfo
}

extend type Mutation {
  # 更新已预约的信息
  updateAppointmentById(appointment: AppointmentInput!): String
  # 更新某一个预约属性
  updateAppointmentByPropName(
    propKey: String!
    propValue: String!
    appointmentId: ID!
    toOutpatientId: ID
  ): String
  moveAppointmentOut(appointmentId: ID!, outpatientId: ID!): String
  deleteAdditionAppointment(appointmentId: ID!, outpatientId: ID!): String
  createQuarterReplaceAddition(
    patientId: ID!
    outpatientId: ID!
    additionIds: [ID]
    appointmentTime: Date!
    # 可用的规律复诊的门诊Id
    mgtOutpatientId: ID
    # 可用的规律复诊的门诊时间
    mgtAppointmentTime: Date
  ): String
  moveQuarterReplaceAddition(
    appointmentId: ID!
    outpatientId: ID!
    additionIds: [ID]
    appointmentTime: Date!
  ): String
  createAddition(
    patientId: ID!
    outpatientId: ID!
    additionIds: [ID]
    appointmentTime: Date!
  ): String
}
