type Appointment {
  _id: ID
  source: String
  appointmentTime: Date
  isTelephoneFollowUp: Boolean
  isOutPatient: Boolean
  status: Int
  type: String
  nickname: String
  hisNumber: String
  mobile: String
  createdAt: Date
  expectedTime: Date
  patientId: ID!
  updatedAt: Date
  confirmStatus: String
  institutionId: ID
  healthCareTeamId: ID
}

type DailyAppointment {
  date: String! # YYYY-MM-DD
  count: Int!
  details: [TeamAppointments!]!
}

type TeamAppointments {
  healthCareTeam: HealthCareTeam!
  count: Int!
}
