input AppointmentInput {
  _id: ID!
  patientId: ID!
  source: String
  appointmentTime: Date
  type: String
  nickname: String
  hisNumber: String
  mobile: String
  confirmStatus: String
  note: String
  blood: Boolean
  footAt: Boolean
  eyeGroundAt: Boolean
  insulinAt: Boolean
  nutritionAt: Boolean
  healthTech: Boolean
  quantizationAt: Boolean
}

type Appointment {
  _id: ID
  source: String
  appointmentTime: Date
  isTelephoneFollowUp: Boolean
  isOutPatient: Boolean
  status: Int
  type: String
  nickname: String
  hisNumber: String
  mobile: String
  createdAt: Date
  expectedTime: Date
  patientId: ID!
  updatedAt: Date
  confirmStatus: String
  institutionId: ID
  healthCareTeamId: ID
  note: String
  blood: Boolean
  footAt: Boolean
  eyeGroundAt: Boolean
  insulinAt: Boolean
  nutritionAt: Boolean
  healthTech: Boolean
  quantizationAt: Boolean
}

type DailyAppointment {
  date: String! # YYYY-MM-DD
  count: Int!
  details: [TeamAppointments!]
}

type TeamAppointments {
  healthCareTeam: HealthCareTeam
  count: Int!
}

extend type Mutation {
  # 更新已预约的信息
  updateAppointmentById(appointment: AppointmentInput!): Boolean
  # 更新某一个预约属性
  updateAppointmentByPropName(
    propKey: String!
    propValue: String!
    appointmentId: ID!
    toOutpatientId: ID
  ): Boolean
}
