scalar Date

enum DeviceModel {
  BG1
}

enum Codename {
  NEEDLE
  IGLUCO
}

type BloodGlucose {
  # defaults to mmol/L | US standard is : mg/dl
  unit: String!
  value: Float!
}

input BloodGlucoseInput {
  # defaults to mmol/L | US standard is : mg/dl
  unit: String!
  value: Float!
}

enum DigestiveState { # NOTE below are usage stats
  #
  # 空腹
  EMPTY_STOMACH
  #
  # 早餐／饭前     早餐前 2641
  BEFORE_BREAKFAST
  #
  # 早餐／饭后     早餐后 913
  AFTER_BREAKFAST
  #
  # 午餐／饭前     午餐前 1311        中餐前 2
  BEFORE_LUNCH
  #
  # 午餐／饭后     午餐后 667         中餐后 5
  AFTER_LUNCH
  #
  # 晚餐／饭前     晚饭前 1137        晚餐前 49
  BEFORE_DINNER
  #
  # 晚餐／饭后     晚饭后 833         晚餐后 38
  AFTER_DINNER
  #
  # 睡前          睡前 15
  BEFORE_BED
  BEFORE_SLEEP
  #
  # 凌晨／半夜     半夜 354           凌晨 5
  BEFORE_DAWN
  MIDNIGHT
  #
  # 零食后        零食后 18
  AFTER_SNACK
  #
  # 随机          随机 74
  # data is 0 or 10                 0 3
  UNKNOWN
}

type Medication {
  type: String
  unit: String
  value: Float
}

type Carbohydrates {
  unit: String
  value: Float
}

input DeviceContextInput {
  # 纬度
  latitude: Float
  # 经度
  longitude: Float
  # 应用名字 The name of the app that was used to connect to the measuring device.
  appName: Codename
  # 应用版本 The version of the app that was used to connect to the measuring device.
  appVersion: String
  isEmulator: Boolean
  isTablet: Boolean
  brand: String
  buildNumber: Int
  bundleId: String
  deviceCountry: String
  deviceId: String
  deviceLocale: String
  manufacturer: String
  # 手机型号 The model of the phone that was used to connect to the measuring device.
  model: String
  readableVersion: String
  # Operating system
  systemName: String
  # Operating system version
  systemVersion: String
  timezone: String
  # Operating system version
  uniqueID: String
  userAgent: String
}

type DeviceContext {
  # 纬度
  latitude: Float
  # 经度
  longitude: Float
  # 应用名字 The name of the app that was used to connect to the measuring device.
  appName: Codename
  # 应用版本 The version of the app that was used to connect to the measuring device.
  appVersion: String
  isEmulator: Boolean
  isTablet: Boolean
  brand: String
  buildNumber: Int
  bundleId: String
  deviceCountry: String
  deviceId: String
  deviceLocale: String
  manufacturer: String
  # 手机型号 The model of the phone that was used to connect to the measuring device.
  model: String
  readableVersion: String
  # Operating system
  systemName: String
  # Operating system version
  systemVersion: String
  timezone: String
  # Operating system version
  uniqueID: String
  userAgent: String
}

type BloodGlucoseMeasurement {
  patient: Patient!
  # 血糖 Measures the pressure in your blood vessels when your heart beats.
  bloodGlucose: BloodGlucose!
  # (e.g. before dinner)
  digestiveState: DigestiveState
  # 手动测量结果 Manually entered test result
  manual: Boolean!
  # a list of medications take before measurement
  medication: [Medication]
  # quantity of carbohydrates consumed before measurement
  carbohydratesConsumed: Carbohydrates
  # had insulin administered before test
  hadTakenInsulin: Boolean
  # The address of the device that was used to take the measurement.
  measurementDeviceAddress: String
  # The model of the device that was used to take the measurement (e.g. BG1)
  measurementDeviceModel: DeviceModel
  # 测量时间
  measuredAt: Date!
  # The device taking the measurement
  deviceContext: DeviceContext
}
