enum CaseRecordStatus {
  first
  quarter
  addition
  year
  darft
}

enum LevelOfBGControl {
  LOOSE
  STRICT
  CUSTOM
  default
}

type BGControlLevel {
  level: LevelOfBGControl
  beforeMealLow: String
  beforeMealHigh: String
  afterMealLow: String
  afterMealHigh: String
  beforeSleepLow: String
  beforeSleepHigh: String
}

type SelfManageFactor {
  factor_0: Boolean
  factor_1: Boolean
  factor_2: Boolean
  factor_3: Boolean
  factor_4: Boolean
  factor_5: Boolean
  factor_6: Boolean
  factor_7: Boolean
  factor_8: Boolean
  factor_9: Boolean
  factor_10: Boolean
  factor_11: Boolean
  factor_12: Boolean
  factor_13: Boolean
  factor_14: Boolean
  factor_15: Boolean
  factor_16: Boolean
  factor_17: Boolean
  factor_Remark: String
}

type NeedOutOfHospitalInterfere {
  interfere_1: Boolean
  interfere_2: Boolean
  interfere_3: Boolean
  interfere_4: Boolean
  interfere_5: Boolean
  interfere_6: Boolean
  interfere_7: Boolean
  interfere_8: Boolean
  interfere_Remark: String
}

type DiscussionComplicationAffect {
  affect_1: Boolean
  affect_2: Boolean
  affect_3: Boolean
  affect_4: Boolean
  affect_5: Boolean
  affect_6: Boolean
  affect_Remark: String
}

type CaseRecordOtherEvaluate {
  BGControlLevel: BGControlLevel
  selfManageFactor: SelfManageFactor
  needOutOfHospitalInterfere: NeedOutOfHospitalInterfere
  discussionComplicationAffect: DiscussionComplicationAffect
}

type Medicine{
    # 药物名
    name:String
    # 口服药一天吃几次 胰岛素一次注射多少质量单位
    frequency:String
    # 药物类型 oral：口服 insulin:胰岛素
    medicineType:String
    # 一次吃多少
    quantity:String
    # 单位
    unit:String
    # 是否分餐
    separateByRelationToMealTime:Boolean
    # 分餐计划
    mealOptions:MealOptions
}

type MealOptions{
  # 早餐前
  beforeBreakfast:String,  
  # 早餐中
  duringBreakfast:String   
  # 早餐后
  afterBreakfast:String  
  # 午餐前  
  beforeLunch:String  
  # 午餐中    
  duringLunch:String  
  # 午餐后    
  afterLunch:String  
  # 晚餐前      
  beforeDinner:String
  # 晚餐中     
  duringDinner:String
  # 晚餐后      
  afterDinner:String
  # 睡前       
  beforeSleep:String       
}

type CRPrescription {
  medicines:[Medicine]
  isTelephoneFollowUp: Boolean
}

type BodyCheckup {
   heert:String
   neck:String
   chest:String
   heart:String
   adb:String
   ext:String
   weight:String
   height:String
   bmi:String
   HP:String
   LP:String
}

type CaseRecordContent {
  prescription: CRPrescription
  bodyCheckup:BodyCheckup
}

type CaseRecord {
  _id: ID!
  createdAt: Date
  caseRecordAt: Date
  status: CaseRecordStatus!
  patient: Patient!
  appointment: Appointment
  doctor: HealthcareProfessional
  caseContent: CaseRecordContent
  otherEvaluate: CaseRecordOtherEvaluate
}
