type ChatMessage {
  content: String!
  senderNickname: String!
  sentAt:String!
}

type ChatMessagesResponse {
  messages: [ChatMessage!]!
  timestamp: String
}

type UnReadMessage {
  chatRoomId: String
  count: Int
}
