enum ReplyType {
  # 评论圈子
  CIRCLE
  # 回复照护师
  CDE
}

type Comments {
  _id: ID!
  # 所评论的圈子的Id
  foodCircleId: String
  # 评论内容
  commentContent: String
  # 评论人Id
  authorId: ID
  # 评论人Name
  authorName: String
  # 评论类型
  type: ReplyType
  # 回复的人的Id
  replyId: ID
  # 回复的评论的ID
  replyToCommentId: ID
  # 回复的人的Name
  replyName: String
  # 点赞
  createdAt: Date
}

input CommentInput {
  foodCircleId: String!
  commentContent: String!
  authorId: ID!
  authorName: String!
  type: ReplyType!
  replyToUserId: ID
  replyToUserName: String
  replyToCommentId: ID
}
