type ConfigurationItem {
  imgUrl: String
  type: String
  recordId: String
}

type ConfigurationContent {
  _id: ID
  type: String
  title: String
  content: [String]
  category: String
  items: [ConfigurationItem]
  createdAt: Date
}

extend type Query {
  getConfigByCategory(category: String!): ConfigurationContent
}
