enum ReplyStatus {
  WAITING_REPLY
  REPLIES
}

enum MeasureTimeType {
  BREAKFAST
  BREAKFAST_SNACK
  LUNCH
  LUNCH_SNACK
  DINNER
  DINNER_SNACK
}

type Foods {
  _id: ID!
  # 测量三餐
  measurementTime: MeasureTimeType
  # 发表朋友圈内容
  circleContet: String
  # 患者ID
  patientId: ID!
  # 患者
  patient: Patient!
  # 发表朋友圈图片
  circleImages: [String]
  # 总评分
  totalScore: String
  # 主食量评分
  mainFoodScore: String
  # 食物热量评分
  foodEnergyScore: String
  # 蛋白量评分
  albumenScore: String
  # 丰富程度评分
  richnessScore: String
  # 创建时间
  createdAt: Date
  # 测量时间
  measuredAt: Date
  # 餐前血糖
  beforeBloodGlucose: [BloodGlucoseRecord]
  # 餐后血糖
  afterBloodGlucose: [BloodGlucoseRecord]
  # 评论列表
  comments: [Comments]
  # 照护师回复状态
  replyStatus: ReplyStatus
  # 最新动态
  latestState: String
  # 操作类型（增 删 改，pubsub用）
  _operation: Operation
  # 操作的具体类型（评星和评论、仅评星、仅评论）
  _operationDetailType: String
  # 修改的内容的ID（评星和评论ID、评星ID、评论ID）
  _recordId: String
  # 徽章记录的ID（在badgeRecords中的记录的ID）
  badgeId: String
  # 徽章记录的创建时间（在badgeRecords中的记录的创建时间）
  badgeCreatedAt: Date
  _senderRole: String
}

input FoodsScoreInput {
  totalScore: String
  mainFoodScore: String
  foodEnergyScore: String
  albumenScore: String
  richnessScore: String
}

type UploadFoodPhotoResult {
  score: Float
  commentList: [comment]
}

type comment {
  comment: String
}
