type HealthCareTeam {
  _id: ID
  name: String!
  institutionName: String
  workDay: [Int]
  institution: Institution!
  healthCareProfessionals: [HealthcareProfessional]
  availableAppointmentDates: [Outpatient]
  institutionId: String
}

extend type Query {
  healthCareTeams: [HealthCareTeam]
}
