type HealthCareTeam {
  _id: ID
  name: String!
  institutionName: String
  institution: Institution!
  healthCareProfessionals: [HealthcareProfessional]
}

extend type Query {
  healthCareTeams: [HealthCareTeam]
}
