type LoginOrSignUpResponse {
  didCreateNewPatient: Boolean!
  _id: ID!
  avatar: String
  nickname: String
  patientState: String
}

extend type Mutation {
  loginOrSignUp(
    mobile: String!
    verificationCode: String!
  ): LoginOrSignUpResponse!
}
