type NeedleChatRoom {
  _id: ID!
  # The users in this chat room
  participants: [User!]!
  messages(before: String, limit: Int = 100): [NeedleChatMessage!]!
  latestMessage: NeedleChatMessage
  # This is specific to the currently logged in user
  unreadMessageCount(userId: ID, nosy: Boolean = false): Int!
  lastSeenAt(userId: ID): Date!
  patient: Patient!
}
