type NeedleImageMessage implements NeedleChatMessage {
  _id: ID!
  imageUrl: String!
  sender: User!
  createdAt: Date!
  messageType: String
  needleChatRoom: NeedleChatRoom!
  sourceType: String
  actualSender: User
  status: MessageStatus
}
