type NeedleTextMessage implements NeedleChatMessage {
  _id: ID!
  text: String!
  sender: User!
  createdAt: Date!
  messageType: String
  needleChatRoom: NeedleChatRoom!
  sourceType: String
  contentType: String
  approved: Boolean
  actualSender: User
  options: [AIContentTypeOption]
}
