input OrderSetDataInput {
  orderStatus: String
}

type OrderCBResult {
  # 下单返回码
  returnCode: String!
  errCode: String
  # 应用ID
  appid: String
  # 微信支付分配的商户号
  partnerid: String
  # 微信返回的支付交易会话ID
  prepayid: String
  # 暂填写固定值Sign=WXPay
  packageName: String
  # 随机字符串
  noncestr: String
  # 时间戳
  timestamp: String
  # 签名
  sign: String
}

type PayOrder {
  # 返回码
  returnCode: String!
  # 错误码
  errCode: String
  # 交易状态
  tradeState: String
}

type Order {
  _id: ID!
  # 病人编号
  patientId: ID!
  #  订单编号
  orderId: ID!
  #  订单时间
  orderTime: Date
  #  订单状态 1：已经下单 2：其他
  orderStatus: String
  #  收货人
  receiver: String
  #  联系电话
  phoneNumber: String
  #  收货地址
  receiveAddress: String
  #  商品类型： 1：iHealth血糖试纸 2：其他
  goodsType: String
  #  商品单价
  goodsUnitPrice: Int
  #  商品规格
  goodsSpecification: String
  #  购买数量
  purchaseQuantity: Int
  #  运费
  freightPrice: Int
  #  总价
  totalPrice: Float
  # 年费服务结束日期
  serviceEndAt: Date
}
