type PhoneFollowUp {
  _id: ID!
  patientId: ID!
  caseRecordId: ID!
  nickname: String
  type: String
  complete: [Boolean]
}

type Task {
  _id: ID!
  patientId: ID!
  type: String
  tasks: [String]
}