type OutpatientPlan {
  _id: ID

  date: String!
  dayOfWeek: DayOfWeek!
  period: PeriodOfDay!

  hospitalId: String!
  hospitalName: String!
  hospital: Institution!
  departmentCode: String
  department: String

  note: String

  patientIds: [ID!]
  patients: [WildPatient!]
  patientsCount: Int!

  signedIds: [ID!]

  createdAt: Date!
  updatedAt: Date!
  _operation: Operation
}

input InputOutpatientPlan {
  date: String!
  period: PeriodOfDay!
  hospitalId: String!
  departmentCode: String!
}

input InputEditWildPatient {
  _id: ID!
  name: String
  mobile: String
  idCard: String
  avatar: String
  disease: [ID!]
  status: WildPatientStatus
  nextVisitDate: String
}

enum DayOfWeek {
  Mon
  Tues
  Wed
  Thur
  Fri
  Sat
  Sun
}

enum PeriodOfDay {
  MORNING
  AFTERNOON
}
