type DailyOutpatients {
  date: String!
  outpatients: [Outpatient!]!
}

enum OutpatientState {
  WAITING
  PROCESSING
  COMPLETED
  CANCELED
}

type OutpatientReport {
  patients: Int
  firstVisits: Int
  returnVisits: Int
  yearVisits: Int
  additionalVisits: Int
}

type OutpatientDutyEmployee {
  name: String!
  phone: String
}

type Outpatient {
  _id: ID
  outpatientDate: Date!
  healthCareTeamId: String
  dayOfWeek: String!
  outpatientPeriod: String!
  doctorName: String!
  hospitalName: String!
  hospitalId: String
  location: String!
  registerPlace: String!
  registerDepartment: String!
  state: OutpatientState!
  note: String
  report: OutpatientReport
  patientIds: [ID!]
  appointmentsId: [ID]
  dutyEmployees: [OutpatientDutyEmployee!]
  createdAt: Date
  updatedAt: Date
  patientsCount: Int!
  appointments: [Appointment!]
  treatmentStates: [TreatmentState!]
  availableAppointmentDates: [Outpatient!]
}
