type DailyOutpatients {
  date: String!
  outpatients: [Outpatient!]!
}

enum OutpatientState {
  # 尚未开诊
  WAITING
  # 正在进行的诊（暂时未用）
  PROCESSING
  # 已完成的诊
  COMPLETED
  # 被取消的诊（包含停诊的状态）
  CANCELED
  # 已被改期的诊
  # MODIFIED
}

type OutpatientReport {
  patients: Int
  firstVisits: Int
  returnVisits: Int
  yearVisits: Int
  additionalVisits: Int
}

type OutpatientDutyEmployee {
  name: String!
  phone: String
}

type Outpatient {
  _id: ID
  outpatientDate: Date!
  healthCareTeamId: String
  dayOfWeek: String!
  outpatientPeriod: String!
  doctorName: String!
  doctorId: String
  hospitalName: String!
  hospitalId: String
  location: String!
  registerPlace: String!
  registerDepartment: String!
  state: OutpatientState!
  note: String
  report: OutpatientReport
  patientIds: [ID!]
  appointmentsId: [ID]
  dutyEmployees: [OutpatientDutyEmployee!]
  createdAt: Date
  updatedAt: Date
  patientsCount: Int!
  appointments: [Appointment!]
  treatmentStates: [TreatmentState!]
  availableAppointmentDates: [Outpatient!]
}
