type Patient {
  _id: ID
  nickname: String
  username: String
  gender: String
  dateOfBirth: Date
  avatar: String
  needleChatRoom: NeedleChatRoom
  footAssessmentPhotos: [Photo]
}

type HealthcareProfessional {
  _id: ID
  nickname: String
  role: String
}
