type Patient {
  _id: ID
  nickname: String
  username: String
  gender: String
  dateOfBirth: String
  diabetesType: String
  startOfIllness: String
  avatar: String
  needleChatRoom: NeedleChatRoom
  footAssessmentPhotos: [Photo]
  closestAppointment: Appointment
  communications: [Communication]
  height: String
  weight: String
  targetWeight: String
  caseRecords: [CaseRecord]
}
