# TODO(jan): Add a Date type and get rid of all the ...AtString parameters

type Query {
  footAssessment(
    patientId: ID!,
    day: String!,
    timezone: String = "+0800",
    # Remove this, the time on the server is accurate, it's just set to GMT
    nowString: String = "1970-01-01T00:00:00.000Z"
  ): FootAssessment!

  footAssessments(
    patientId: ID!  
  ): [FootAssessment!]!

  treatmentState(
    patientId: ID!,
    day: String,
    timezone: String = "+0800"
  ): TreatmentState!

  treatmentStates(
    day: String,
    timezone: String = "+0800"
  ): [TreatmentState!]!

  photos(patientId: ID!, owner: String!): [Photo!]!

  chatMessages(appointmentId: ID!): ChatMessagesResponse!

  # Statistics
  totalTimeAtClinic: [DataPointNumberNumber!]!
  timeBetweenAppointments: [DataPointNumberNumberStdDev!]!
  activePatients: [DataPointNumberNumber!]!
}

type Mutation {
  saveFootAssessment(
    recordId: ID!,
    updatedAtString: String!,
    assessmentDetailsJson: String!,
    treatmentStateId: ID!,
    footBloodAt: Boolean
  ): String

  savePhoto(
    patientId: ID!,
    data: String!,
    owner: String!,
    note: String!
  ): Boolean!

  saveAssessmentTimes(
    treatmentStateId: String!,
    role: String!,
    startAtString: String!,
    stopAtString: String!
  ): Boolean!

  saveChatMessage(
    content: String!,
    sentAtString: String!,
    appointmentId: ID!,
    senderNickname: String!
  ): Boolean!
}

schema {
  query: Query
  mutation: Mutation
}
