type Query {
  footAssessment(
    patientId: ID!,
    day: String!,
    timezone: String = "+0800"
  ): FootAssessment!

  treatmentState(
    patientId: ID!,
    day: String,
    timezone: String = "+0800"
  ): TreatmentState!

  treatmentStates(
    day: String,
    timezone: String = "+0800"
  ): [TreatmentState!]!

  photos(patientId: ID!, owner: String!): [Photo!]!
}

type Mutation {
  saveFootAssessment(
    recordId: ID!,
    updatedAtString: String!,
    assessmentDetailsJson: String!,
    treatmentStateId: ID!,
    footBloodAt: Boolean
  ): String

  savePhoto(
    patientId: ID!,
    data: String!,
    owner: String!,
  ): Boolean!

  signInPatient(patientId: String!): SignInEvent
  signOutPatient(patientId: String!): SignOutRes

  createEvent(payload: String!): Boolean!
}

schema {
  query: Query
  mutation: Mutation
}
