schema {
  query: Query
  mutation: Mutation
}

type Query {
  appointments(day: String, timezone: String = "+0800"): [Appointment]
}

type Mutation {
  createFootAssessment(params:FootAssessmentInput, stringifiedInput:String):FootAssessment!
  createEvent(payload: String!): Boolean!
  setFootAssessmentCompleteFlag(_id: ID):Boolean!
  signInPatient(patientId: ID!): SignInEvent
  signOutPatient(patientId: ID!): SignInEvent
}