schema {
  query: Query
  mutation: Mutation
}

type StringResult {
  error: String
  result: String
}

type AssessmentStateResult {
  error: String
  result: AssessmentState
}

type Query {
  appointments(day: String, timezone: String = "+0800"): [Appointment]
  patient(id: ID!): Patient
}

type Mutation {
  createFootAssessment(payload: String!): StringResult!
  setAssessmentState(
    patientId: ID!,
    assessment: Assessment!,
    state: AssessmentState!
  ): AssessmentStateResult!

  createEvent(payload: String!): Boolean!
  savePhoto(
    patientId: ID!,
    data: String!,
    context: PHOTO_CONTEXT!,
    notes: String
  ): Boolean!

  signInPatient(patientId: ID!): SignInEvent
  signOutPatient(patientId: ID!): SignInEvent
}