schema {
  query: Query
  mutation: Mutation
}

type Query {
  appointments(day: String, timezone: String = "+0800"): [Appointment]
  patients: [Patient]
  patient(_id: ID): Patient
  footAssessments(patientId: ID): [FootAssessment]
  footAssessment(_id: ID): FootAssessment
  events(limit: Int = 3): [Event]
  bloodTests(patientId: ID): [BloodTest]
  task(patientId: ID!): Task
  tasks: [Task]
  phoneFollowUp(patientId: ID!): PhoneFollowUp
}

type Mutation {
  createFootAssessment(params:FootAssessmentInput, stringifiedInput:String):FootAssessment!
  createEvent(params:EventInput):Event!
  setFootAssessmentCompleteFlag(_id: ID):Boolean!
}