enum Uses {
    BLOOD_GLUCOSE_DOCTOR
    BLOOD_GLUCOSE_ASSISTANT
    BLOOD_PRESSURE_DOCTOR
    BLOOD_PRESSURE_ASSISTANT
}

enum SoapCategory {
  MEDICINE
  MONITOR
  DIET
  SOLUTION
  SPORTS
  HEALTH_ADJUSTMENT
  REDUCE_RISK
}

enum SoapSegment {
  SUBJECTIVE
  OBJECTIVE
  ASSESSMENT
  PLAN
}

type Sentence {
  _id: ID!
  category: SoapCategory
  group: String
  segment: SoapSegment
  author: String
  value: String
  createdAt: Date!
  dependence: ID
  recentUseAt: Date
  usedFor: Uses
}