enum FinishReason {
  manually
  timeout
}

enum SessionInitiator {
  PATIENT
  ASSISTANT
  SYSTEM
}

type Session {
  _id: ID!
  type: String
  chatRoomId: ID!
  startAt: Date!
  endAt: Date
  finishReason: FinishReason
  educatorName: String
  initiator: SessionInitiator
  createdAt: Date
  _operation: Operation
}
