type SignInEvent {
  eventRes: SignEvt
  checkInRes: Boolean
}

type SignEvt {
  patientId: ID
  patientName: String
  createdAt: String
  isSignedOut: Boolean
  type: String
}

type TreatmentStateEvent {
  _id: ID
  patientId: ID
  appointmentTime: String
  checkIn: Boolean
}

type SignOutRes {
  isSignedOut: Boolean
}
