type TaskSoapPlan {
  relatedAssessmentCode: String!
  content: String!
}

type TaskSoap {
  _id: ID!
  taskId: ID!
  patientId: ID!
  assessments: [String]
  plans: [TaskSoapPlan]
  byTel: Boolean!
  createdAt: Date
  updatedAt: Date
}

input TaskSoapPlanInput {
  relatedAssessmentCode: String!
  content: String!
}
input TaskSoapInput {
  patientId: ID!
  taskId: ID!
  assessments: [String]
  plans: [TaskSoapPlanInput]
  byTel: Boolean!
}
