type TaskSoapPlan {
  assessment: Assessment
  content: String
}

type TaskSoap {
  _id: ID!
  taskId: ID!
  patientId: ID!
  plans: [TaskSoapPlan]
  byTel: Boolean!
  createdAt: Date
  updatedAt: Date
}

input TaskSoapPlanInput {
  assessmentId: ID!
  content: String!
}
input TaskSoapInput {
  patientId: ID!
  taskId: ID!
  plans: [TaskSoapPlanInput]
  byTel: Boolean!
  operatorId: ID
}
