type Warning {
  _id: ID
  createdAt: Date
  dinnerSituation: String
  bgValue: String
  bloodGlucoseValue: Float
  nickname: String
  gender: String
  mobile: String
  patientId: ID
  dateOfBirth: Date
  patient: Patient
  appointmentTime: Date
  count: Int
}
