type WildPatient {
  # 姓名
  name: String!
  # 头像
  avatar: String
  # 手机号
  mobile: String
  # 身份证号
  idCard: String
  # 状态（是否已转为共同照护用户）
  status: WildPatientStatus!
  # 病种
  disease: [Disease!]
  # 门诊附加信息（此字段内容不是保存在WildPatient表中而是从门诊表获取得到）
  outpatientExtra: [OutpatientExtraData!]
}

input InputWildPatient {
  name: String!
  mobile: String!
  idCard: String!
}

enum WildPatientStatus {
  FIRST_VISIT
  NOT_FIRST_VISIT
}

type OutpatientExtraData {
  mobile: String
  disease: [Disease!]
  doctor: String
  nextVisitDate: String
}
